
    build:
      context: .
      args:
        # IMPORTANT: Insert the official server.jar URL here (see README)
        MC_SERVER_JAR_URL: ${MC_SERVER_JAR_URL}
    container_name: mc-server
    ports:
      - "8888:25565"
    env_file:
      - .env
    volumes:
      - mc-data:/minecraft
    restart: unless-stopped

volumes:
  mc-data: